# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acqGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.T2settingsGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.T2settingsGrp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.T2settingsGrp.setFlat(False)
        self.T2settingsGrp.setObjectName("T2settingsGrp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.T2settingsGrp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.T2settingsGrp)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.T2chn1Chk_3 = QtWidgets.QCheckBox(self.T2settingsGrp)
        self.T2chn1Chk_3.setChecked(True)
        self.T2chn1Chk_3.setObjectName("T2chn1Chk_3")
        self.gridLayout_2.addWidget(self.T2chn1Chk_3, 0, 1, 1, 1)
        self.T2chn2Chk_3 = QtWidgets.QCheckBox(self.T2settingsGrp)
        self.T2chn2Chk_3.setChecked(True)
        self.T2chn2Chk_3.setObjectName("T2chn2Chk_3")
        self.gridLayout_2.addWidget(self.T2chn2Chk_3, 0, 2, 1, 1)
        self.T2syncFrame_3 = QtWidgets.QFrame(self.T2settingsGrp)
        self.T2syncFrame_3.setObjectName("T2syncFrame_3")
        self.T2syncLayout_3 = QtWidgets.QFormLayout(self.T2syncFrame_3)
        self.T2syncLayout_3.setObjectName("T2syncLayout_3")
        self.T2syncZeroLabel_3 = QtWidgets.QLabel(self.T2syncFrame_3)
        self.T2syncZeroLabel_3.setObjectName("T2syncZeroLabel_3")
        self.T2syncLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.T2syncZeroLabel_3)
        self.T2syncLevelLabel_3 = QtWidgets.QLabel(self.T2syncFrame_3)
        self.T2syncLevelLabel_3.setObjectName("T2syncLevelLabel_3")
        self.T2syncLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.T2syncLevelLabel_3)
        self.T2syncOffsetLabel_3 = QtWidgets.QLabel(self.T2syncFrame_3)
        self.T2syncOffsetLabel_3.setObjectName("T2syncOffsetLabel_3")
        self.T2syncLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.T2syncOffsetLabel_3)
        self.T2syncOffsetValue_3 = QtWidgets.QSpinBox(self.T2syncFrame_3)
        self.T2syncOffsetValue_3.setMinimum(-99999)
        self.T2syncOffsetValue_3.setMaximum(99999)
        self.T2syncOffsetValue_3.setObjectName("T2syncOffsetValue_3")
        self.T2syncLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.T2syncOffsetValue_3)
        self.T2syncZeroValue_3 = QtWidgets.QSpinBox(self.T2syncFrame_3)
        self.T2syncZeroValue_3.setMinimum(-40)
        self.T2syncZeroValue_3.setMaximum(0)
        self.T2syncZeroValue_3.setObjectName("T2syncZeroValue_3")
        self.T2syncLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T2syncZeroValue_3)
        self.T2syncLevelValue_3 = QtWidgets.QSpinBox(self.T2syncFrame_3)
        self.T2syncLevelValue_3.setMinimum(-1200)
        self.T2syncLevelValue_3.setMaximum(0)
        self.T2syncLevelValue_3.setObjectName("T2syncLevelValue_3")
        self.T2syncLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.T2syncLevelValue_3)
        self.gridLayout_2.addWidget(self.T2syncFrame_3, 1, 0, 1, 1)
        self.T2chn1Frame_3 = QtWidgets.QFrame(self.T2settingsGrp)
        self.T2chn1Frame_3.setObjectName("T2chn1Frame_3")
        self.T2chn1Layout_3 = QtWidgets.QFormLayout(self.T2chn1Frame_3)
        self.T2chn1Layout_3.setObjectName("T2chn1Layout_3")
        self.T2chn1ZeroLabel_3 = QtWidgets.QLabel(self.T2chn1Frame_3)
        self.T2chn1ZeroLabel_3.setObjectName("T2chn1ZeroLabel_3")
        self.T2chn1Layout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.T2chn1ZeroLabel_3)
        self.T2chn1ZeroValue_3 = QtWidgets.QSpinBox(self.T2chn1Frame_3)
        self.T2chn1ZeroValue_3.setMinimum(-40)
        self.T2chn1ZeroValue_3.setMaximum(0)
        self.T2chn1ZeroValue_3.setObjectName("T2chn1ZeroValue_3")
        self.T2chn1Layout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T2chn1ZeroValue_3)
        self.T2chn1LevelLabel_3 = QtWidgets.QLabel(self.T2chn1Frame_3)
        self.T2chn1LevelLabel_3.setObjectName("T2chn1LevelLabel_3")
        self.T2chn1Layout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.T2chn1LevelLabel_3)
        self.T2chn1LevelValue_3 = QtWidgets.QSpinBox(self.T2chn1Frame_3)
        self.T2chn1LevelValue_3.setMinimum(-1200)
        self.T2chn1LevelValue_3.setMaximum(0)
        self.T2chn1LevelValue_3.setObjectName("T2chn1LevelValue_3")
        self.T2chn1Layout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.T2chn1LevelValue_3)
        self.T2chn1OffsetLabel_3 = QtWidgets.QLabel(self.T2chn1Frame_3)
        self.T2chn1OffsetLabel_3.setObjectName("T2chn1OffsetLabel_3")
        self.T2chn1Layout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.T2chn1OffsetLabel_3)
        self.T2chn1OffsetValue_3 = QtWidgets.QSpinBox(self.T2chn1Frame_3)
        self.T2chn1OffsetValue_3.setMinimum(-99999)
        self.T2chn1OffsetValue_3.setMaximum(99999)
        self.T2chn1OffsetValue_3.setObjectName("T2chn1OffsetValue_3")
        self.T2chn1Layout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.T2chn1OffsetValue_3)
        self.gridLayout_2.addWidget(self.T2chn1Frame_3, 1, 1, 1, 1)
        self.T2chn2Frame_3 = QtWidgets.QFrame(self.T2settingsGrp)
        self.T2chn2Frame_3.setObjectName("T2chn2Frame_3")
        self.T2chn2Layout_3 = QtWidgets.QFormLayout(self.T2chn2Frame_3)
        self.T2chn2Layout_3.setObjectName("T2chn2Layout_3")
        self.T2chn2ZeroLabel_3 = QtWidgets.QLabel(self.T2chn2Frame_3)
        self.T2chn2ZeroLabel_3.setObjectName("T2chn2ZeroLabel_3")
        self.T2chn2Layout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.T2chn2ZeroLabel_3)
        self.T2chn2LevelLabel_3 = QtWidgets.QLabel(self.T2chn2Frame_3)
        self.T2chn2LevelLabel_3.setObjectName("T2chn2LevelLabel_3")
        self.T2chn2Layout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.T2chn2LevelLabel_3)
        self.T2chn2OffsetLabel_3 = QtWidgets.QLabel(self.T2chn2Frame_3)
        self.T2chn2OffsetLabel_3.setObjectName("T2chn2OffsetLabel_3")
        self.T2chn2Layout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.T2chn2OffsetLabel_3)
        self.T2chn2OffsetValue_3 = QtWidgets.QSpinBox(self.T2chn2Frame_3)
        self.T2chn2OffsetValue_3.setMinimum(-99999)
        self.T2chn2OffsetValue_3.setMaximum(99999)
        self.T2chn2OffsetValue_3.setObjectName("T2chn2OffsetValue_3")
        self.T2chn2Layout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.T2chn2OffsetValue_3)
        self.T2chn2ZeroValue_3 = QtWidgets.QSpinBox(self.T2chn2Frame_3)
        self.T2chn2ZeroValue_3.setMinimum(-40)
        self.T2chn2ZeroValue_3.setMaximum(0)
        self.T2chn2ZeroValue_3.setObjectName("T2chn2ZeroValue_3")
        self.T2chn2Layout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T2chn2ZeroValue_3)
        self.T2chn2LevelValue_3 = QtWidgets.QSpinBox(self.T2chn2Frame_3)
        self.T2chn2LevelValue_3.setMinimum(-1200)
        self.T2chn2LevelValue_3.setMaximum(0)
        self.T2chn2LevelValue_3.setObjectName("T2chn2LevelValue_3")
        self.T2chn2Layout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.T2chn2LevelValue_3)
        self.gridLayout_2.addWidget(self.T2chn2Frame_3, 1, 2, 1, 1)
        self.T2saveDefaultPrmBtn = QtWidgets.QPushButton(self.T2settingsGrp)
        self.T2saveDefaultPrmBtn.setObjectName("T2saveDefaultPrmBtn")
        self.gridLayout_2.addWidget(self.T2saveDefaultPrmBtn, 2, 0, 1, 2)
        self.T2applySetBtn_3 = QtWidgets.QPushButton(self.T2settingsGrp)
        self.T2applySetBtn_3.setObjectName("T2applySetBtn_3")
        self.gridLayout_2.addWidget(self.T2applySetBtn_3, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.T2settingsGrp)
        self.T2acqGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.T2acqGrp.setObjectName("T2acqGrp")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.T2acqGrp)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_17 = QtWidgets.QLabel(self.T2acqGrp)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 2, 1, 1, 1)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.T2acqTimePerFileLabel_3 = QtWidgets.QLabel(self.T2acqGrp)
        self.T2acqTimePerFileLabel_3.setObjectName("T2acqTimePerFileLabel_3")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.T2acqTimePerFileLabel_3)
        self.T2acqTimePerFileValue_3 = QtWidgets.QSpinBox(self.T2acqGrp)
        self.T2acqTimePerFileValue_3.setMaximum(6000)
        self.T2acqTimePerFileValue_3.setObjectName("T2acqTimePerFileValue_3")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T2acqTimePerFileValue_3)
        self.T2acqNoFilesLabel_3 = QtWidgets.QLabel(self.T2acqGrp)
        self.T2acqNoFilesLabel_3.setObjectName("T2acqNoFilesLabel_3")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.T2acqNoFilesLabel_3)
        self.T2acqNoFilesValue_3 = QtWidgets.QSpinBox(self.T2acqGrp)
        self.T2acqNoFilesValue_3.setMaximum(6000)
        self.T2acqNoFilesValue_3.setObjectName("T2acqNoFilesValue_3")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.T2acqNoFilesValue_3)
        self.gridLayout_10.addLayout(self.formLayout_9, 3, 0, 2, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.T2modeTriple_3 = QtWidgets.QRadioButton(self.T2acqGrp)
        self.T2modeTriple_3.setChecked(True)
        self.T2modeTriple_3.setObjectName("T2modeTriple_3")
        self.horizontalLayout_7.addWidget(self.T2modeTriple_3)
        self.T2modeDouble_3 = QtWidgets.QRadioButton(self.T2acqGrp)
        self.T2modeDouble_3.setChecked(False)
        self.T2modeDouble_3.setObjectName("T2modeDouble_3")
        self.horizontalLayout_7.addWidget(self.T2modeDouble_3)
        self.gridLayout_10.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.T2filenameLabel_3 = QtWidgets.QLabel(self.T2acqGrp)
        self.T2filenameLabel_3.setObjectName("T2filenameLabel_3")
        self.horizontalLayout_8.addWidget(self.T2filenameLabel_3)
        self.T2filenameBtn_3 = QtWidgets.QPushButton(self.T2acqGrp)
        self.T2filenameBtn_3.setObjectName("T2filenameBtn_3")
        self.horizontalLayout_8.addWidget(self.T2filenameBtn_3)
        self.T2filenameValue_3 = QtWidgets.QLineEdit(self.T2acqGrp)
        self.T2filenameValue_3.setClearButtonEnabled(True)
        self.T2filenameValue_3.setObjectName("T2filenameValue_3")
        self.horizontalLayout_8.addWidget(self.T2filenameValue_3)
        self.gridLayout_10.addLayout(self.horizontalLayout_8, 6, 0, 1, 3)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.T2timeGateLongLabel_3 = QtWidgets.QLabel(self.T2acqGrp)
        self.T2timeGateLongLabel_3.setObjectName("T2timeGateLongLabel_3")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.T2timeGateLongLabel_3)
        self.T2timeGateShortLabel_3 = QtWidgets.QLabel(self.T2acqGrp)
        self.T2timeGateShortLabel_3.setObjectName("T2timeGateShortLabel_3")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.T2timeGateShortLabel_3)
        self.T2timeGateLongValue_3 = QtWidgets.QSpinBox(self.T2acqGrp)
        self.T2timeGateLongValue_3.setMaximum(20000)
        self.T2timeGateLongValue_3.setObjectName("T2timeGateLongValue_3")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T2timeGateLongValue_3)
        self.T2timeGateShortValue_3 = QtWidgets.QSpinBox(self.T2acqGrp)
        self.T2timeGateShortValue_3.setMaximum(20000)
        self.T2timeGateShortValue_3.setObjectName("T2timeGateShortValue_3")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.T2timeGateShortValue_3)
        self.gridLayout_10.addLayout(self.formLayout_10, 3, 1, 2, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.T2startBtn_3 = QtWidgets.QPushButton(self.T2acqGrp)
        self.T2startBtn_3.setMinimumSize(QtCore.QSize(197, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.T2startBtn_3.setFont(font)
        self.T2startBtn_3.setObjectName("T2startBtn_3")
        self.horizontalLayout_9.addWidget(self.T2startBtn_3)
        self.T2stopBtn_3 = QtWidgets.QPushButton(self.T2acqGrp)
        self.T2stopBtn_3.setMinimumSize(QtCore.QSize(196, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.T2stopBtn_3.setFont(font)
        self.T2stopBtn_3.setObjectName("T2stopBtn_3")
        self.horizontalLayout_9.addWidget(self.T2stopBtn_3)
        self.gridLayout_10.addLayout(self.horizontalLayout_9, 7, 1, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.T2acqGrp)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_10.addWidget(self.line_3, 1, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.T2acqGrp)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 2, 0, 1, 1)
        self.T2doHistChk_3 = QtWidgets.QCheckBox(self.T2acqGrp)
        self.T2doHistChk_3.setObjectName("T2doHistChk_3")
        self.gridLayout_10.addWidget(self.T2doHistChk_3, 5, 0, 1, 1)
        self.line_3.raise_()
        self.label_12.raise_()
        self.T2doHistChk_3.raise_()
        self.label_17.raise_()
        self.verticalLayout.addWidget(self.T2acqGrp)
        self.progGrp = QtWidgets.QGroupBox(self.centralwidget)
        self.progGrp.setObjectName("progGrp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.progGrp)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.progGrp)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.commandOutput = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.commandOutput.setMinimumSize(QtCore.QSize(321, 179))
        self.commandOutput.setReadOnly(True)
        self.commandOutput.setPlainText("")
        self.commandOutput.setObjectName("commandOutput")
        self.verticalLayout_4.addWidget(self.commandOutput)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.acqProgLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.acqProgLabel.setObjectName("acqProgLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.acqProgLabel)
        self.acqProgBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.acqProgBar.setProperty("value", 0)
        self.acqProgBar.setObjectName("acqProgBar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acqProgBar)
        self.acqProgFileLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.acqProgFileLabel.setObjectName("acqProgFileLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.acqProgFileLabel)
        self.acqProgFileBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.acqProgFileBar.setProperty("value", 0)
        self.acqProgFileBar.setObjectName("acqProgFileBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.acqProgFileBar)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_3.addWidget(self.label_34)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rateSyncLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.rateSyncLabel.setObjectName("rateSyncLabel")
        self.gridLayout.addWidget(self.rateSyncLabel, 0, 0, 1, 1)
        self.rateChn1Label = QtWidgets.QLabel(self.layoutWidget1)
        self.rateChn1Label.setObjectName("rateChn1Label")
        self.gridLayout.addWidget(self.rateChn1Label, 0, 1, 1, 1)
        self.rateChn2Label = QtWidgets.QLabel(self.layoutWidget1)
        self.rateChn2Label.setObjectName("rateChn2Label")
        self.gridLayout.addWidget(self.rateChn2Label, 0, 2, 1, 1)
        self.rateSyncValue = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateSyncValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateSyncValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateSyncValue.setObjectName("rateSyncValue")
        self.gridLayout.addWidget(self.rateSyncValue, 1, 0, 1, 1)
        self.rateChn1Value = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateChn1Value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateChn1Value.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateChn1Value.setObjectName("rateChn1Value")
        self.gridLayout.addWidget(self.rateChn1Value, 1, 1, 1, 1)
        self.rateChn2Value = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateChn2Value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateChn2Value.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateChn2Value.setObjectName("rateChn2Value")
        self.gridLayout.addWidget(self.rateChn2Value, 1, 2, 1, 1)
        self.rateDoubleLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.rateDoubleLabel.setObjectName("rateDoubleLabel")
        self.gridLayout.addWidget(self.rateDoubleLabel, 2, 0, 1, 1)
        self.rateTripleLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.rateTripleLabel.setObjectName("rateTripleLabel")
        self.gridLayout.addWidget(self.rateTripleLabel, 2, 1, 1, 1)
        self.rateTotalLabel_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.rateTotalLabel_2.setObjectName("rateTotalLabel_2")
        self.gridLayout.addWidget(self.rateTotalLabel_2, 2, 2, 1, 1)
        self.rateDoubleValue = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateDoubleValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateDoubleValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateDoubleValue.setObjectName("rateDoubleValue")
        self.gridLayout.addWidget(self.rateDoubleValue, 3, 0, 1, 1)
        self.rateTripleValue = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateTripleValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateTripleValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateTripleValue.setObjectName("rateTripleValue")
        self.gridLayout.addWidget(self.rateTripleValue, 3, 1, 1, 1)
        self.rateTotalValue = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.rateTotalValue.setFrameShadow(QtWidgets.QFrame.Plain)
        self.rateTotalValue.setDigitCount(12)
        self.rateTotalValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rateTotalValue.setObjectName("rateTotalValue")
        self.gridLayout.addWidget(self.rateTotalValue, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.progGrp)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.T2settingsGrp.setTitle(_translate("MainWindow", "Settings"))
        self.label_9.setText(_translate("MainWindow", "Sync / channel 0 (1274 keV)"))
        self.T2chn1Chk_3.setText(_translate("MainWindow", "Channel 1 (511 keV)"))
        self.T2chn2Chk_3.setText(_translate("MainWindow", "Channel 2 (511 keV)"))
        self.T2syncZeroLabel_3.setText(_translate("MainWindow", "CFD zero cross (mV)"))
        self.T2syncLevelLabel_3.setText(_translate("MainWindow", "CFD level (mV)"))
        self.T2syncOffsetLabel_3.setText(_translate("MainWindow", "Chn offset (ps)"))
        self.T2chn1ZeroLabel_3.setText(_translate("MainWindow", "CFD zero cross (mV)"))
        self.T2chn1LevelLabel_3.setText(_translate("MainWindow", "CFD level (mV)"))
        self.T2chn1OffsetLabel_3.setText(_translate("MainWindow", "Chn offset (ps)"))
        self.T2chn2ZeroLabel_3.setText(_translate("MainWindow", "CFD zero cross (mV)"))
        self.T2chn2LevelLabel_3.setText(_translate("MainWindow", "CFD level (mV)"))
        self.T2chn2OffsetLabel_3.setText(_translate("MainWindow", "Chn offset (ps)"))
        self.T2saveDefaultPrmBtn.setText(_translate("MainWindow", "Save current parameters as default"))
        self.T2applySetBtn_3.setText(_translate("MainWindow", "Apply settings"))
        self.T2acqGrp.setTitle(_translate("MainWindow", "Acquisition"))
        self.label_17.setText(_translate("MainWindow", "Gating parameters"))
        self.T2acqTimePerFileLabel_3.setText(_translate("MainWindow", "Acq time per file (min)"))
        self.T2acqNoFilesLabel_3.setText(_translate("MainWindow", "Total number of files"))
        self.T2modeTriple_3.setText(_translate("MainWindow", "Triple coincidence"))
        self.T2modeDouble_3.setText(_translate("MainWindow", "Double coincidence"))
        self.T2filenameLabel_3.setText(_translate("MainWindow", "Output file name"))
        self.T2filenameBtn_3.setText(_translate("MainWindow", "Pick a file"))
        self.T2timeGateLongLabel_3.setText(_translate("MainWindow", "time gate long (ps)"))
        self.T2timeGateShortLabel_3.setText(_translate("MainWindow", "time gate 511 (ps)"))
        self.T2startBtn_3.setText(_translate("MainWindow", "Start"))
        self.T2stopBtn_3.setText(_translate("MainWindow", "Stop"))
        self.label_12.setText(_translate("MainWindow", "Acquisition parameters"))
        self.T2doHistChk_3.setText(_translate("MainWindow", "Do histrogramming"))
        self.progGrp.setTitle(_translate("MainWindow", "Progress and control"))
        self.label_2.setText(_translate("MainWindow", "Commnand output"))
        self.commandOutput.setPlaceholderText(_translate("MainWindow", "Command output"))
        self.label_3.setText(_translate("MainWindow", "Acquisition progress"))
        self.acqProgLabel.setText(_translate("MainWindow", "Current acquisition"))
        self.acqProgFileLabel.setText(_translate("MainWindow", "Current file"))
        self.label_34.setText(_translate("MainWindow", "Counting rates (cnts/sec):"))
        self.rateSyncLabel.setText(_translate("MainWindow", "Sync/chn 0"))
        self.rateChn1Label.setText(_translate("MainWindow", "channel 1"))
        self.rateChn2Label.setText(_translate("MainWindow", "channel 2"))
        self.rateDoubleLabel.setText(_translate("MainWindow", "Double coinc"))
        self.rateTripleLabel.setText(_translate("MainWindow", "Triple coinc"))
        self.rateTotalLabel_2.setText(_translate("MainWindow", "Total"))

